mode: debug
connectionString: "user=postgres password=HappyDay$123 host=localhost port=5432 dbname=happy_day"
logger:
  mode: text
isCorEnable: true
staticSite: "./wwwroot/mec-app/dist/mec-app/pt-BR"